services:
  postgres:
    image: postgres:latest
    container_name: fafo_postgres
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5440:5432"
    networks:
      - pg
networks:
  pg:
    driver: bridge
volumes:
  postgres: {}

